In [1]:
# Task 1
import numpy as np
arr1 = np.ones((5,5))
arr1[1:-1,1:-1] = 0

print(arr1)

# Task 2
np.random.seed(42)
random_data = np.random.randn(100, 3)

normalized_data = (random_data -random_data.mean(axis =0)) / random_data.std(axis=0)

print("Means: ",np.mean(normalized_data,axis=0))
print("Standard Deviations: ",np.std(normalized_data,axis=0))

# Task 3
X = np.random.randn(50, 3)
true_theta = np.array([2.5, -1.2, 3.7])
y = X @ true_theta + np.random.randn(50) * 0.1


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
Means:  [-2.60902411e-17  1.55431223e-17 -8.88178420e-18]
Standard Deviations:  [1. 1. 1.]
